// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package model

import (
	"database/sql"
)

type Book struct {
	ID           int64
	Title        string
	Sort         sql.NullString
	Timestamp    sql.NullTime
	Pubdate      sql.NullTime
	SeriesIndex  float64
	AuthorSort   sql.NullString
	Isbn         interface{}
	Lccn         interface{}
	Path         interface{}
	Flags        int64
	Uuid         sql.NullString
	HasCover     sql.NullBool
	LastModified interface{}
}
