// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"database/sql"
	"time"
)

type Book struct {
	ID           uint16
	Title        string
	Sort         sql.NullString
	Timestamp    time.Time
	Pubdate      time.Time
	SeriesIndex  float64
	AuthorSort   string
	Isbn         string
	Lccn         string
	Path         string
	Flags        int64
	Uuid         sql.NullString
	HasCover     sql.NullBool
	LastModified time.Time
}
